name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

env:
  CARGO_TERM_COLOR: always


jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - run: cargo fmt --all -- --check

  docs_and_spell_check:
    name: Docs and Spell Check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      RUSTDOCFLAGS: "-Dwarnings"
    steps:
      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Check spelling
        uses: crate-ci/typos@master

      - run: cargo doc --no-deps

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy

      - name: "Run clippy"
        run: cargo clippy --all

  build_and_test_linux:
    name: Build check (Linux)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Install dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: "Build"
        run: cargo build

  build_windows:
    name: Build check (Windows)
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - name: Prepare symlink configuration
        run: git config --global core.symlinks true

      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@nextest
      - name: "Build"
        run: cargo build

  build_macos:
    name: Build check (MacOS)
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Prepare symlink configuration
        run: git config --global core.symlinks true

      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@nextest
      - name: "Build"
        run: cargo build
